// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: api/file/v1/file.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	File_ListByHostname_FullMethodName        = "/api.file.v1.File/ListByHostname"
	File_GetDetailByHostname_FullMethodName   = "/api.file.v1.File/GetDetailByHostname"
	File_DownloadByHostname_FullMethodName    = "/api.file.v1.File/DownloadByHostname"
	File_DownloadDirByHostname_FullMethodName = "/api.file.v1.File/DownloadDirByHostname"
	File_ListNode_FullMethodName              = "/api.file.v1.File/ListNode"
)

// FileClient is the client API for File service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileClient interface {
	ListByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error)
	GetDetailByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error)
	DownloadByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error)
	DownloadDirByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error)
	ListNode(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error)
}

type fileClient struct {
	cc grpc.ClientConnInterface
}

func NewFileClient(cc grpc.ClientConnInterface) FileClient {
	return &fileClient{cc}
}

func (c *fileClient) ListByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileReply)
	err := c.cc.Invoke(ctx, File_ListByHostname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) GetDetailByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileReply)
	err := c.cc.Invoke(ctx, File_GetDetailByHostname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) DownloadByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileReply)
	err := c.cc.Invoke(ctx, File_DownloadByHostname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) DownloadDirByHostname(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileReply)
	err := c.cc.Invoke(ctx, File_DownloadDirByHostname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileClient) ListNode(ctx context.Context, in *ListFileRequest, opts ...grpc.CallOption) (*ListFileReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFileReply)
	err := c.cc.Invoke(ctx, File_ListNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServer is the server API for File service.
// All implementations must embed UnimplementedFileServer
// for forward compatibility.
type FileServer interface {
	ListByHostname(context.Context, *ListFileRequest) (*ListFileReply, error)
	GetDetailByHostname(context.Context, *ListFileRequest) (*ListFileReply, error)
	DownloadByHostname(context.Context, *ListFileRequest) (*ListFileReply, error)
	DownloadDirByHostname(context.Context, *ListFileRequest) (*ListFileReply, error)
	ListNode(context.Context, *ListFileRequest) (*ListFileReply, error)
	mustEmbedUnimplementedFileServer()
}

// UnimplementedFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileServer struct{}

func (UnimplementedFileServer) ListByHostname(context.Context, *ListFileRequest) (*ListFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByHostname not implemented")
}
func (UnimplementedFileServer) GetDetailByHostname(context.Context, *ListFileRequest) (*ListFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetailByHostname not implemented")
}
func (UnimplementedFileServer) DownloadByHostname(context.Context, *ListFileRequest) (*ListFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadByHostname not implemented")
}
func (UnimplementedFileServer) DownloadDirByHostname(context.Context, *ListFileRequest) (*ListFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadDirByHostname not implemented")
}
func (UnimplementedFileServer) ListNode(context.Context, *ListFileRequest) (*ListFileReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNode not implemented")
}
func (UnimplementedFileServer) mustEmbedUnimplementedFileServer() {}
func (UnimplementedFileServer) testEmbeddedByValue()              {}

// UnsafeFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServer will
// result in compilation errors.
type UnsafeFileServer interface {
	mustEmbedUnimplementedFileServer()
}

func RegisterFileServer(s grpc.ServiceRegistrar, srv FileServer) {
	// If the following call pancis, it indicates UnimplementedFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&File_ServiceDesc, srv)
}

func _File_ListByHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).ListByHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_ListByHostname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).ListByHostname(ctx, req.(*ListFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_GetDetailByHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).GetDetailByHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_GetDetailByHostname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).GetDetailByHostname(ctx, req.(*ListFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_DownloadByHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).DownloadByHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_DownloadByHostname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).DownloadByHostname(ctx, req.(*ListFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_DownloadDirByHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).DownloadDirByHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_DownloadDirByHostname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).DownloadDirByHostname(ctx, req.(*ListFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _File_ListNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServer).ListNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: File_ListNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServer).ListNode(ctx, req.(*ListFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// File_ServiceDesc is the grpc.ServiceDesc for File service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var File_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.file.v1.File",
	HandlerType: (*FileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByHostname",
			Handler:    _File_ListByHostname_Handler,
		},
		{
			MethodName: "GetDetailByHostname",
			Handler:    _File_GetDetailByHostname_Handler,
		},
		{
			MethodName: "DownloadByHostname",
			Handler:    _File_DownloadByHostname_Handler,
		},
		{
			MethodName: "DownloadDirByHostname",
			Handler:    _File_DownloadDirByHostname_Handler,
		},
		{
			MethodName: "ListNode",
			Handler:    _File_ListNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/file/v1/file.proto",
}
