server:
  http:
    addr: 0.0.0.0:8003
    timeout: 100s
  grpc:
#    addr: 0.0.0.0:9005
    timeout: 100s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
consul:
  addr: 127.0.0.1:8500